version: '3'

services:

  web:
    # command: bundle exec bin/webpack-dev-server
    # command: bundle exec foreman start -f Procfile.dev
    build: .
    ports:
      - 8080:8080
      - 80:80
    volumes:
      - .:/var/www/ark
    depends_on:
      - db

  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=m4g1c!
