# config/app.yml for rails-settings-cached
defaults: &defaults
  foo: "Foo"
  bar: 123
  app:
    repo: "https://github.com/divxzero/ark"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
