# config/app.yml for rails-settings-cached
defaults: &defaults
  config:
    repo:
      url: 'https://github.com/DivXZero/cancan'
      username: ''
      password: ''
    database:
      sql: ''
    app:
      autoUpdate: true

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
